package com.metacube.eadSession5.enums;

public enum Response {
	SUCCESS, FAILURE, INVALID_QUANTITY,
	PRODUCT_NOT_FOUND, USER_NOT_FOUND, SHOPPING_CART_NOT_FOUND,
	DUPLICATE_PRODUCT_ID, DUPLICATE_USER_ID,
	INVALID_USER, INVALID_PRODUCT, INVALID_SHOPPING_CART;
}
